#baseURL = 'cartasaomeupequeno.l58.me'
title = 'Cartas Ao Meu Pequeno'
author = "Lucas Sousa de Oliveira"
# copyright = "Copyright © 2008–2019, Steve Francia and the lee.so; all rights reserved."
paginate = 10
languageCode = "pt-BR"
DefaultContentLanguage = "pt"
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson", "alt-error"]
relativeURLs = true
#canonifyURLs = true

theme = "PaperMod"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

enableGitInfo = true
timeout = "5m"
noBuildLock = true

[minify]
  minifyOutput = true

[params]
  subtitle = "Um pouquinho do papai para você, leãozinho."
  defaultColor = "auto" # set color mode: dark, light, auto
  mainSections = ['post']
  footer = "Te amo, pequeno. Assinado: Papai."

  DateFormat = "2 de January de 2006"
  disableSpecial1stPost = true
  #hideSummary = true
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true

  postsIntro = "Oi pequeno,"

[menu]
  [[menu.main]]
    name = "Cartas do Papai"
    url = "/cartasdopapai"
    weight = 20

  [[menu.main]]
    name = "Cartas da Mamãe"
    url = "/cartasdamamae"
    weight = 20

  [[menu.main]]
    name = "Todas as Cartas"
    url = "/"
    weight = 30

[permalinks]
  posts = "/:year-:month-:day-:title/"

[markup.goldmark.renderer]
  # Allows HTML in Markdown
  unsafe = true

[imaging]
  anchor = 'Smart'
  bgColor = '#ffffff'
  hint = 'photo'
  quality = 85
  resampleFilter = 'Box'
